/*
 * This source code is auto-generated by blanco Framework.
 */
package blanco.keygenerator.enums

/**
 * Enumerations of Key Types.
 */
enum class BlancoKeyGeneratorKeyTypes(val code: Int, val type: String) {
    /** Key Type RAW. */
    RAW(1, "raw"),
    /** Kye Type Base64 encoded */
    B64(2, "b64"),
    /** Key Type hexadecimal */
    HEX(3, "hex"),
    /** Key Type of binary number */
    BIN(4, "bin"),
    /** Key Type of SHA1 encoded */
    SHA1(5, "sha1"),
    /** Key Type of SHA256 encoded */
    SHA256(6, "sha256")
}
