/*
 * This source code is auto-generated by blanco Framework.
 */
package blanco.keygenerator.valueobjects

/**
 * Key Structure of BlancoKeyGenerator.
 */
data class BlancoKeyGeneratorKey constructor(
    val number: Int,
    val name: String,
    val keyPart: List<BlancoKeyGeneratorKeyPhrase>,
    val valuePart: List<BlancoKeyGeneratorKeyPhrase>
)
