/*
 * This source code is auto-generated by blanco Framework.
 */
package blanco.keygenerator.valueobjects

/**
 * Item structure of BlacoKeyGenerator keys.
 */
data class BlancoKeyGeneratorKeyPhrase constructor(
    val name: String,
    val type: String,
    val length: Int
)
