/*
 * This source code is auto-generated by blanco Framework.
 */
package blanco.keygenerator.exceptions

/**
 * Exception for BlancoKeyGenerator.
 */
class BlancoKeyGeneratorException : Exception {
    constructor(msg: String) : super(msg)
    constructor(msg: String, e: Throwable) : super(msg, e)
    constructor(code: String, msg: String) : super(msg)
    constructor(code: String, msg: String, e: Throwable) : super(msg, e)
}
