/*
 * This source code is auto-generated by blanco Framework.
 */
package blanco.keygenerator

/**
 * Constants for BlancoKeyGenerator.
 */
class BlancoKeyGeneratorConstants {
    companion object {
        /** Key item separator */
        const val KEY_SEPARATOR = "%"
        /** Key string encoding charset */
        const val KEY_ENCODING = "UTF-8"
    }
}
